name: FIAP - MODULO 03 - IAC

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  TF_VERSION: '1.15.4'
  TF_WORKING_DIR: 'terraform-modules'
  EKS_CLUSTER_NAME: 'eks-cluster-01'

jobs:
  infrastructure:
    name: 'AWS - TERRAFORM - INFRASTRUCTURE'
    runs-on: ubuntu-latest
    environment: 'APPLY_APPROVAL'
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: AWS Credentials - Configure
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Terraform - Setup
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform - Init - Infrastructure
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          echo "================ Terraform - Init ================"
          echo "Date/Time: $(date '+%Y-%m-%d %H:%M:%S')"
          echo "--------------------------------------------------"

          echo "##[section]Initializing Terraform..."
          terraform init \
            -backend-config="bucket=${{ vars.AWS_BUCKET_IAC_NAME }}" \
            -backend-config="key=${{ vars.AWS_BUCKET_IAC_FOLDER_NAME }}"

      - name: Terraform - Validate - Infrastructure
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          echo "============== Terraform - Validate =============="
          echo "Date/Time: $(date '+%Y-%m-%d %H:%M:%S')"
          echo "--------------------------------------------------"

          echo "##[section]Validating the Infrastructure..."
          terraform validate

      - name: Terraform - Plan - Infrastructure
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          echo "================ Terraform - Plan ================"
          echo "Date/Time: $(date '+%Y-%m-%d %H:%M:%S')"
          echo "--------------------------------------------------"

          echo "##[section]Planning the Infrastructure..."
          terraform plan \
            -var="aws_region=${{ vars.AWS_REGION }}" \
            -var="eks_cluster_name=${{ env.EKS_CLUSTER_NAME }}" \
            -var="db_user=${{ secrets.DB_USER }}" \
            -var="db_pass=${{ secrets.DB_PASS }}"

      - name: Terraform - Apply - Infrastructure
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          echo "=============== Terraform - Apply ================"
          echo "Date/Time: $(date '+%Y-%m-%d %H:%M:%S')"
          echo "--------------------------------------------------"

          echo "##[section]Applying the Infrastructure..."
          terraform apply -auto-approve \
            -var="aws_region=${{ vars.AWS_REGION }}" \
            -var="eks_cluster_name=${{ env.EKS_CLUSTER_NAME }}" \
            -var="db_user=${{ secrets.DB_USER }}" \
            -var="db_pass=${{ secrets.DB_PASS }}"

  addons:
    name: 'AWS - TERRAFORM - ADDONS'
    needs: infrastructure
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: AWS Credentials - Configure
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Terraform - Setup
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: EKS Cluster - Setup
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: EKS Cluster - Connect
        run: |
          echo "============= EKS Cluster - Connect =============="
          echo "Date/Time: $(date '+%Y-%m-%d %H:%M:%S')"
          echo "--------------------------------------------------"

          echo "##[section]Connecting to the EKS Cluster..."
          aws eks update-kubeconfig --region ${{ vars.AWS_REGION }} --name ${{ env.EKS_CLUSTER_NAME }}

      - name: Terraform - Init - Addons
        working-directory: ${{ env.TF_WORKING_DIR }}/addons
        run: |
          echo "================ Terraform - Init ================"
          echo "Date/Time: $(date '+%Y-%m-%d %H:%M:%S')"
          echo "--------------------------------------------------"

          echo "##[section]Initializing Terraform..."
          terraform init \
            -backend-config="bucket=${{ vars.AWS_BUCKET_ADDONS_NAME }}" \
            -backend-config="key=${{ vars.AWS_BUCKET_ADDONS_FOLDER_NAME}}"

      - name: Terraform - Validate - Addons
        working-directory: ${{ env.TF_WORKING_DIR }}/addons
        run: |
          echo "============== Terraform - Validate =============="
          echo "Date/Time: $(date '+%Y-%m-%d %H:%M:%S')"
          echo "--------------------------------------------------"

          echo "##[section]Validating the Addons..."
          terraform validate

      - name: Terraform - Plan - Addons
        working-directory: ${{ env.TF_WORKING_DIR }}/addons
        run: |
          echo "================ Terraform - Plan ================"
          echo "Date/Time: $(date '+%Y-%m-%d %H:%M:%S')"
          echo "--------------------------------------------------"

          echo "##[section]Planning the Addons..."
          terraform plan \
            -var="aws_region=${{ vars.AWS_REGION }}" \
            -var="eks_cluster_name=${{ env.EKS_CLUSTER_NAME }}" \
            -var="eks_argocd_domain_name=${{ vars.ARGOCD_DOMAIN_NAME }}" \
            -var="aws_bucket_iac_name=${{ vars.AWS_BUCKET_IAC_NAME }}" \
            -var="aws_bucket_iac_folder_name=${{ vars.AWS_BUCKET_IAC_FOLDER_NAME }}" \

      - name: Terraform - Apply - Addons
        working-directory: ${{ env.TF_WORKING_DIR }}/addons
        run: |
          echo "=============== Terraform - Apply ================"
          echo "Date/Time: $(date '+%Y-%m-%d %H:%M:%S')"
          echo "--------------------------------------------------"

          echo "##[section]Applying the Addons..."
          terraform apply -auto-approve \
            -var="aws_region=${{ vars.AWS_REGION }}" \
            -var="eks_cluster_name=${{ env.EKS_CLUSTER_NAME }}" \
            -var="eks_argocd_domain_name=${{ vars.ARGOCD_DOMAIN_NAME }}" \
            -var="aws_bucket_iac_name=${{ vars.AWS_BUCKET_IAC_NAME }}" \
            -var="aws_bucket_iac_folder_name=${{ vars.AWS_BUCKET_IAC_FOLDER_NAME }}"

  configs:
    name: 'AWS - CONFIGS'
    needs: addons
    runs-on: ubuntu-latest
    env:
      EKS_NAMESPACE: 'eks-namespace'
      EKS_INGRESS_NAME: 'ingress-nginx'
      EKS_INGRESS_NAMESPACE: 'ingress-nginx'
      EKS_CERT_MANAGER_NAMESPACE: 'cert-manager'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: AWS Credentials - Configure
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: EKS Cluster - Setup
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: EKS Cluster - Connect
        run: |
          echo "============= EKS Cluster - Connect =============="
          echo "Date/Time: $(date '+%Y-%m-%d %H:%M:%S')"
          echo "--------------------------------------------------"

          echo "##[section]Connecting to the EKS Cluster..."
          aws eks update-kubeconfig --region ${{ vars.AWS_REGION }} --name ${{ env.EKS_CLUSTER_NAME }}

      - name: Ingress Nginx - Apply Rules
        run: |
          echo "================= Ingress Nginx =================="
          echo "Date/Time: $(date '+%Y-%m-%d %H:%M:%S')"
          echo "--------------------------------------------------"

          echo "##[section]Applying the Ingress Nginx Rules..."
          kubectl wait --namespace ${{ env.EKS_INGRESS_NAMESPACE }} \
            --for=condition=ready pod \
            --selector=app.kubernetes.io/component=controller \
            --timeout=180s
          kubectl apply -f eks-templates/ingress-rules.yml
          sleep 3

          echo "##[section]Validating the Ingress Nginx Services..."
          kubectl get service --namespace ${{ env.EKS_INGRESS_NAMESPACE }} ingress-nginx-controller

      - name: Cert-Manager - Apply Rules
        run: |
          echo "================== Cert-Manager =================="
          echo "Date/Time: $(date '+%Y-%m-%d %H:%M:%S')"
          echo "--------------------------------------------------"

          echo "##[section]Applying Cert-Manager Rules..."
          kubectl wait --namespace ${{ env.EKS_CERT_MANAGER_NAMESPACE }} \
            --for=condition=Available deployment/cert-manager-webhook \
            --timeout=180s
          kubectl apply -f eks-templates/cert-manager-rules.yml
          sleep 3

          echo "##[section]Validating the Cert-Manager Pods..."
          kubectl get pods --namespace ${{ env.EKS_CERT_MANAGER_NAMESPACE }}

      - name: Route53 - Update
        run: |
          echo "================ Route53 - Update ================"
          echo "Date/Time: $(date '+%Y-%m-%d %H:%M:%S')"
          echo "--------------------------------------------------"

          echo "##[section]Waiting for the NGINX Service to provision the NLB..."
          NLB_DNS=""
          while [ -z "$NLB_DNS" ]; do
            NLB_DNS=$(kubectl get svc ingress-nginx-controller --namespace ${{ env.EKS_INGRESS_NAMESPACE }} --output jsonpath='{.status.loadBalancer.ingress[0].hostname}')

            if [ -z "$NLB_DNS" ]; then
              echo "##[section]Waiting another 10 seconds..."
              sleep 10
            fi
          done
          echo "##[section]New NLB Detected: $NLB_DNS"

          cat <<EOF > route53-update.json
          {
            "Comment": "Automatic NLB update via GitHub Actions",
            "Changes": [
              {
                "Action": "UPSERT",
                "ResourceRecordSet": {
                  "Name": "${{ vars.APIS_DOMAIN_NAME }}",
                  "Type": "CNAME",
                  "TTL": 60,
                  "ResourceRecords": [
                    {
                      "Value": "$NLB_DNS"
                    }
                  ]
                }
              },
              {
                "Action": "UPSERT",
                "ResourceRecordSet": {
                  "Name": "${{ vars.ARGOCD_DOMAIN_NAME }}",
                  "Type": "CNAME",
                  "TTL": 60,
                  "ResourceRecords": [
                    {
                      "Value": "$NLB_DNS"
                    }
                  ]
                }
              }
            ]
          }
          EOF

          echo "##[section]Updating Route53..."
          aws route53 change-resource-record-sets --hosted-zone-id ${{ secrets.HOSTED_ZONE_ID }} --change-batch file://route53-update.json

  destroy:
    name: 'AWS - TERRAFORM - DESTROY'
    runs-on: ubuntu-latest
    environment: 'DESTROY_APPROVAL'
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: AWS Credentials - Configure
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Terraform - Setup
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform - Init - Addons
        working-directory: ${{ env.TF_WORKING_DIR }}/addons
        run: |
          echo "================ Terraform - Init ================"
          echo "Date/Time: $(date '+%Y-%m-%d %H:%M:%S')"
          echo "--------------------------------------------------"

          echo "##[section]Initializing Terraform..."
          terraform init \
            -backend-config="bucket=${{ vars.AWS_BUCKET_ADDONS_NAME }}" \
            -backend-config="key=${{ vars.AWS_BUCKET_ADDONS_FOLDER_NAME}}"

      - name: Terraform - Destroy - Addons
        working-directory: ${{ env.TF_WORKING_DIR }}/addons
        run: |
          echo "============== Terraform - Destroy ==============="
          echo "Date/Time: $(date '+%Y-%m-%d %H:%M:%S')"
          echo "--------------------------------------------------"

          echo "##[section]Destroying the Addons..."
          terraform destroy -auto-approve \
            -var="aws_region=${{ vars.AWS_REGION }}" \
            -var="eks_cluster_name=${{ env.EKS_CLUSTER_NAME }}" \
            -var="eks_argocd_domain_name=${{ vars.ARGOCD_DOMAIN_NAME }}" \
            -var="aws_bucket_iac_name=${{ vars.AWS_BUCKET_IAC_NAME }}" \
            -var="aws_bucket_iac_folder_name=${{ vars.AWS_BUCKET_IAC_FOLDER_NAME }}"

      - name: Terraform - Init - Infrastructure
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          echo "================ Terraform - Init ================"
          echo "Date/Time: $(date '+%Y-%m-%d %H:%M:%S')"
          echo "--------------------------------------------------"

          echo "##[section]Initializing Terraform..."
          terraform init \
            -backend-config="bucket=${{ vars.AWS_BUCKET_IAC_NAME }}" \
            -backend-config="key=${{ vars.AWS_BUCKET_IAC_FOLDER_NAME }}"

      - name: Terraform - Destroy - Infrastructure
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          echo "============== Terraform - Destroy ==============="
          echo "Date/Time: $(date '+%Y-%m-%d %H:%M:%S')"
          echo "--------------------------------------------------"

          echo "##[section]Destroying the Infrastructure..."
          terraform destroy -auto-approve \
            -var="aws_region=${{ vars.AWS_REGION }}" \
            -var="eks_cluster_name=${{ env.EKS_CLUSTER_NAME }}" \
            -var="db_user=${{ secrets.DB_USER }}" \
            -var="db_pass=${{ secrets.DB_PASS }}"