name: FIAP - MODULO 03 - IAC

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_BUCKET_NAME: ${{ vars.AWS_BUCKET_NAME }}
  TF_VERSION: '1.15.4'
  TF_WORKING_DIR: 'terraform-modules'
  EKS_CLUSTER_NAME: 'eks-cluster-01'
  EKS_NAMESPACE: 'ms-namespace-01'
  EKS_INGRESS_NAME: 'ms-ingress-01'
  EKS_INGRESS_NAMESPACE: 'ms-namespace-ingress-01'
  EKS_CERT_MANAGER_NAMESPACE: 'ms-cert-manager-01'
  EKS_KEDA_NAMESPACE: 'ms-keda-01'

jobs:
  apply:
    name: 'AWS - TERRAFORM - APPLY'
    runs-on: ubuntu-latest
    environment: 'APPLY_APPROVAL'
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Configure - AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform - Setup
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform - Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |

          echo "================= Terraform Init ================="
          echo "Date/Time: $(date '+%Y-%m-%d %H:%M:%S')"
          echo "--------------------------------------------------"

          echo "##[section]Initializing Terraform..."
          terraform init \
            -backend-config="bucket=${{ env.AWS_BUCKET_NAME }}" \
            -backend-config="key=iac-general/terraform.tfstate"

      - name: Terraform - Validate
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |

          echo "=============== Terraform Validate ==============="
          echo "Date/Time: $(date '+%Y-%m-%d %H:%M:%S')"
          echo "--------------------------------------------------"

          echo "##[section]Validating the Infrastructure..."
          terraform validate

      - name: Terraform - Plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |

          echo "================= Terraform Plan ================="
          echo "Date/Time: $(date '+%Y-%m-%d %H:%M:%S')"
          echo "--------------------------------------------------"

          echo "##[section]Planning the Infrastructure..."
          terraform plan \
            -var="aws_region=${{ env.AWS_REGION }}" \
            -var="db_user=${{ secrets.DB_USER }}" \
            -var="db_pass=${{ secrets.DB_PASS }}"

      - name: Terraform - Apply
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |

          echo "================ Terraform Apply ================="
          echo "Date/Time: $(date '+%Y-%m-%d %H:%M:%S')"
          echo "--------------------------------------------------"

          echo "##[section]Applying the Infrastructure..."
          terraform apply -auto-approve \
            -var="aws_region=${{ env.AWS_REGION }}" \
            -var="db_user=${{ secrets.DB_USER }}" \
            -var="db_pass=${{ secrets.DB_PASS }}"

      - name: Terraform - Outputs
        id: tf-outputs
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |

          echo "=============== Terraform Outputs ================"
          echo "Date/Time: $(date '+%Y-%m-%d %H:%M:%S')"
          echo "--------------------------------------------------"

          echo "##[section]Getting the output values from the Infrastructure..."
          KEDA_ARN=$(terraform output -raw keda_sqs_role_arn)
          echo "KEDA_ARN=$KEDA_ARN" >> $GITHUB_ENV

  eks-config:
    name: 'AWS - EKS-CONFIG'
    needs: apply
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Configure - AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup - EKS Cluster
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Connect - EKS Cluster
        run: |

          echo "============= Connect - EKS Cluster =============="
          echo "Date/Time: $(date '+%Y-%m-%d %H:%M:%S')"
          echo "--------------------------------------------------"

          echo "##[section]Connecting to the EKS Cluster..."
          aws eks update-kubeconfig --region ${{ vars.AWS_REGION }} --name ${{ env.EKS_CLUSTER_NAME }}

      - name: Install - Metrics Server
        run: |

          echo "============ Install - Metrics Server ============"
          echo "Date/Time: $(date '+%Y-%m-%d %H:%M:%S')"
          echo "--------------------------------------------------"

          echo "##[section]Installing the Metrics Server..."
          kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
          sleep 10

          echo "##[section]Validating the Metrics Server..."
          kubectl get pods --namespace kube-system

      - name: Install - Ingress Nginx
        run: |

          echo "============ Install - Ingress Nginx ============="
          echo "Date/Time: $(date '+%Y-%m-%d %H:%M:%S')"
          echo "--------------------------------------------------"

          echo "##[section]Installing the Ingress Nginx..."
          kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.10.1/deploy/static/provider/aws/deploy.yaml
          sleep 10

          echo "##[section]Applying the Ingress Nginx Rules..."
          kubectl wait --namespace ${{ env.EKS_INGRESS_NAMESPACE }} \
            --for=condition=ready pod \
            --selector=app.kubernetes.io/component=controller \
            --timeout=180s
          kubectl apply -f eks-templates/ingress-rules.yml
          sleep 3

          echo "##[section]Validating the Ingress Nginx Services..."
          kubectl get service --namespace ${{ env.EKS_INGRESS_NAMESPACE }} ingress-nginx-controller

      - name: Install - Cert-Manager
        run: |

          echo "============= Install - Cert-Manager ============="
          echo "Date/Time: $(date '+%Y-%m-%d %H:%M:%S')"
          echo "--------------------------------------------------"

          echo "##[section]Installing the Cert-Manager..."
          kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.14.4/cert-manager.yaml
          sleep 10

          echo "##[section]Applying Cert-Manager Rules..."
          kubectl wait --namespace ${{ env.EKS_CERT_MANAGER_NAMESPACE }} \
            --for=condition=Available deployment/cert-manager-webhook \
            --timeout=180s
          kubectl apply -f eks-templates/cert-manager-rules.yml
          sleep 3

          echo "##[section]Validating the Cert-Manager Pods..."
          kubectl get pods --namespace ${{ env.EKS_CERT_MANAGER_NAMESPACE }}

      - name: Install - KEDA
        run: |

          echo "================= Install - KEDA ================="
          echo "Date/Time: $(date '+%Y-%m-%d %H:%M:%S')"
          echo "--------------------------------------------------"

          echo "##[section]Installing KEDA..."
          helm repo add kedacore https://kedacore.github.io/charts
          helm repo update

          helm install keda kedacore/keda \
            --create-namespace \
            --namespace ${{ env.EKS_KEDA_NAMESPACE }} \
            --set serviceAccount.operator.annotations."eks\.amazonaws\.com/role-arn"="${{ env.KEDA_ARN }}" \
            --set serviceAccount.metricServer.annotations."eks\.amazonaws\.com/role-arn"="${{ env.KEDA_ARN }}"

      - name: Route53 - Update
        run: |

          echo "================= Update Route53 ================="
          echo "Date/Time: $(date '+%Y-%m-%d %H:%M:%S')"
          echo "--------------------------------------------------"

          echo "##[section]Waiting for the Ingress to provision the NLB..."
          NLB_DNS=""
          while [ -z "$NLB_DNS" ]; do
            NLB_DNS=$(kubectl get ingress ${{ env.EKS_INGRESS_NAME }} --namespace ${{ env.EKS_NAMESPACE }} --output jsonpath='{.status.loadBalancer.ingress[0].hostname}')

            if [ -z "$NLB_DNS" ]; then
              echo "##[section]Waiting another 10 seconds..."
              sleep 10
            fi
          done
          echo "##[section]New NLB Detected: $NLB_DNS"

          cat <<EOF > route53-update.json
          {
            "Comment": "Automatic NLB update via GitHub Actions",
            "Changes": [
              {
                "Action": "UPSERT",
                "ResourceRecordSet": {
                  "Name": "$DOMAIN_NAME",
                  "Type": "CNAME",
                  "TTL": 60,
                  "ResourceRecords": [
                    {
                      "Value": "$NLB_DNS"
                    }
                  ]
                }
              }
            ]
          }
          EOF

          echo "##[section]Updating Route53..."
          aws route53 change-resource-record-sets --hosted-zone-id ${{ secrets.HOSTED_ZONE_ID }} --change-batch file://route53-update.json

  destroy:
    name: 'AWS - TERRAFORM - DESTROY'
    runs-on: ubuntu-latest
    environment: 'DESTROY_APPROVAL'
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Configure - AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform - Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |

          echo "================= Terraform Init ================="
          echo "Date/Time: $(date '+%Y-%m-%d %H:%M:%S')"
          echo "--------------------------------------------------"

          echo "##[section]Initializing Terraform..."
          terraform init \
            -backend-config="bucket=${{ env.AWS_BUCKET_NAME }}" \
            -backend-config="key=iac-general/terraform.tfstate"

      - name: Terraform - Destroy
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |

          echo "=============== Terraform Destroy ==============="
          echo "Date/Time: $(date '+%Y-%m-%d %H:%M:%S')"
          echo "--------------------------------------------------"

          echo "##[section]Destroying the Infrastructure..."
          terraform destroy -auto-approve \
            -var="aws_region=${{ env.AWS_REGION }}" \
            -var="db_user=${{ secrets.DB_USER }}" \
            -var="db_pass=${{ secrets.DB_PASS }}"